FROM node:18-alpine
WORKDIR /app

# 最新のビルド済みファイルをコピー
ADD deploy.tar.gz .

# 必要な依存関係をインストール
RUN npm install --production

# 環境変数設定
ENV NEXT_PUBLIC_API_URL=https://miraim-backend.icymoss-273d47c5.australiaeast.azurecontainerapps.io
ENV NODE_ENV=production
ENV ENVIRONMENT=production

EXPOSE 3000
CMD ["npm", "start"]
