# 開発環境用 Docker Compose
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://backend:8000
    env_file:
      - ./config/.env.development
    depends_on:
      - backend
    networks:
      - miraim-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./config/.env.development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - miraim-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - miraim-network


networks:
  miraim-network:
    driver: bridge

volumes:
  mysql_dev_data: